### ISSUE TITLE
Frequently seeing "Invalid stream (wrong magic numbers)" in plugin display

### ISSUE THREAD

**Issue by DrewTheRat** [WPIRoboticsProjects/GRIP-SmartDashboard#2]
We added the plugin to the SmartDashboard and it shows the image with the contour. However, it frequently flashes a blank pinkish screen with the message "Invalid stream (wrong magic numbers)" on it.
I see this message in [GRIPExtension.java](https://github.com/WPIRoboticsProjects/GRIP-SmartDashboard/blob/master/src/main/java/edu/wpi/grip/smartdashboard/GRIPExtension.java).

**Comment by gartaud** [comment]
Me too :-) Thanks for looking into it.

**Comment by gartaud** [comment]
Cross-referencing https://github.com/WPIRoboticsProjects/GRIP/issues/407

**Comment by gartaud** [comment]
Drew, I added some extra info in the other thread. I may try again with a webcam tonight.

**Comment by DrewTheRat** [comment]
All the conversation about this happened here: https://github.com/WPIRoboticsProjects/GRIP/issues/407

This issue is fixed, so closing.
